development:
  clients:
    default:
      database: demo_backend_development
      hosts:
        - localhost:27017
      options:
        server_selection_timeout: 5
  options:
    raise_not_found_error: false
