development:
  clients:
    default:
      database: demo_backend_development
      hosts:
        - localhost:27017
      options:
        server_selection_timeout: 5

test:
  clients:
    default:
      database: demo_backend_test
      hosts:
        - localhost:27017
      options:
        server_selection_timeout: 5

production:
  clients:
    default:
      database: demo_backend_production
      hosts:
        - localhost:27017
      options:
        user: <%= ENV['MONGO_USER'] %>
        password: <%= ENV['MONGO_PASSWORD'] %>
